spring.datasource.url=jdbc:postgresql://localhost:5432/stocksimulator
spring.datasource.username=varshith
spring.datasource.password=//keep you password of databse

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
